---

- name: VECTOR | Copy Daemon script
  template:
    src: "{{ vector_service_template_path }}"
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: root
    group: root
  notify: Restart vector

- name: VECTOR | Configuring service
  systemd:
    name: vector
    state: "{{ vector_service_state }}"
    enabled: "{{ vector_service_enabled }}"
    daemon_reload: yes
